apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-gist-api
  namespace: gist-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-gist-api
  template:
    metadata:
      labels:
        app: github-gist-api
    spec:
      containers:
      - name: github-gist-api
        image: cherukudocker/github-gist-api:11
        ports:
        - containerPort: 8080
