apiVersion: v1
kind: Service
metadata:
  name: github-gist-api
  namespace: gist-api
spec:
  type: NodePort
  selector:
    app: github-gist-api
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
